### ISSUE TITLE
Do you need the .obj files or .dll files?

### ISSUE THREAD

**Issue by edwinyzh** [isemenkov/libpasmyhtml#1]
Thanks for sharing this library, I'm interested to see how it works, I assume you'll need the .dll or .dll obj files? Where can we get it? Thanks in advance.

**Comment by isemenkov** [comment]
You can find some examples at [unit-tests/myhtmltestcase.pas](https://github.com/isemenkov/libpasmyhtml/blob/master/unit-tests/myhtmltestcase.pas) file. And in short future I add more examples usage at [examples](https://github.com/isemenkov/libpasmyhtml/tree/master/examples) folder.

About object files it is only bindings [source/libpasmyhtml.pas](https://github.com/isemenkov/libpasmyhtml/blob/master/source/libpasmyhtml.pas) and thin wrapper [source/pasmyhtml.pas](https://github.com/isemenkov/libpasmyhtml/blob/master/source/pasmyhtml.pas) for [myhtml library](https://github.com/lexborisov/myhtml). You need donwload it and compile using Makefile to have object and dynamic library files.
If you working on linux operational system you can install [myhtml-dev package](https://packagecloud.io/Modest/myhtml).

**Comment by edwinyzh** [comment]
Thanks for your comment @isemenkov !

Just one suggestion - provided a pre-compiled .DLL file for Windows users if you can, just like many other DLL wrappers do :)

**Comment by isemenkov** [comment]
Ok
